import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ConfigProvider} from "antd";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ConfigProvider theme={{
            components: {
                Input: {
                    borderRadius: 16,
                    paddingBlock: 8
                }
            }
        }}>
            {children}
        </ConfigProvider>
        </body>
        </html>
    );
}
