import type {Metadata} from "next";

// import {Noto_Sans_Mongolian,} from "next/font/google";
import {ConfigProvider} from "antd";
import "./globals.scss";

// const mongolian = Noto_Sans_Mongolian({
//     subsets: ["latin"],
//     weight: ['400'],
// });
import local from 'next/font/local';

const contentFont = local({
    src: [
        {
            path: './styles/fonts/calibri.ttf',
            weight: '800',
        },
    ],
    variable: '--font-content',
});
const titleFont = local({
    src: [
        {
            path: './styles/fonts/monbaiti.ttf',
            weight: '800',
        },
    ],
    variable: '--font-title',
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${titleFont.variable} ${contentFont.variable}`}>
        <ConfigProvider theme={{
            components: {
                Input: {
                    borderRadius: 16,
                    paddingBlock: 8
                }
            }
        }}>
            {children}
        </ConfigProvider>
        </body>
        </html>
    );
}
